name: ci

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: yarn install

      - name: Run Jest tests
        run: yarn test